export const CHANNELS_API_RESPONSE = {
  channels: [
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "lp",
      url: "https://warpcast.com/~/channel/lp",
      name: "HAM 🍖",
      description:
        "The home of $TN100x and Ham. Tip Ham 🍖 backed by $TN100x. Learn more: https://ham.fun CA: 0x5b5dee44552546ecea05edea01dcd7be7aa6144a",
      image_url: "https://i.imgur.com/vC00Vn0.png",
      lead_fid: 4482,
      host_fids: null,
      created_at: "2024-02-04T17:05:03+00:00",
      follower_count: 44284,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "alphathailand",
      url: "https://warpcast.com/~/channel/alphathailand",
      name: "Thai Community แชร์ข่าวสาร🇹🇭",
      description:
        "🇹🇭Thailand $degen exchange  👉🏻วิธีการทิป $degen ต้องเข้าไปทิปที่ cast ของเจ้าตัวนะคะ ถ้าเจ้าของโพสทิปคืนในคอมเม้นเรา เราจะไม่ได้\n\n👉🏻เชค $degenที่ได้ในแต่ละวันได้ที่ degen.tips \n\n👉🏻ช่วยๆกันโพสสาระ หากใครเห็นว่าดีช่วยๆกันกด $degen ให้เพื่อนๆกันค่ะ",
      image_url: "https://i.imgur.com/MeXCEo1.jpg",
      lead_fid: 271497,
      host_fids: null,
      created_at: "2024-02-05T16:52:19+00:00",
      follower_count: 2701,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "bullposting",
      url: "https://warpcast.com/~/channel/bullposting",
      name: "bullposting",
      description: "a safe space for euphoric bullposting. HIGHER",
      image_url: "https://i.imgur.com/BPPmoNb.jpg",
      lead_fid: 7143,
      host_fids: null,
      created_at: "2024-02-08T01:29:57+00:00",
      follower_count: 975,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "selfhelp",
      url: "https://warpcast.com/~/channel/selfhelp",
      name: "selfhelp",
      description:
        "If you have some favorite quotes, books, or learned something new that impacted you in a positive way, feel free to join and share. 💙",
      image_url:
        "https://imagedelivery.net/BXluQx4ige9GuW0Ia56BHw/465c6dbe-d2cc-475a-e286-f32588269300/rectcrop3",
      lead_fid: 227912,
      host_fids: null,
      created_at: "2024-04-19T19:05:05+00:00",
      follower_count: 852,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "alpha",
      url: "https://warpcast.com/~/channel/alpha",
      name: "alpha",
      description: "insights and strategies for better investing",
      image_url: "https://i.imgur.com/PK1xauQ.jpg",
      lead_fid: 4085,
      host_fids: null,
      created_at: "2023-12-16T18:55:29+00:00",
      follower_count: 728,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "alphadrops",
      url: "https://warpcast.com/~/channel/alphadrops",
      name: "Airdrops Community",
      description: "Web3 early projects and airdrops",
      image_url:
        "https://imagedelivery.net/BXluQx4ige9GuW0Ia56BHw/a7be6e6d-7b58-48c5-5506-02bfb6667c00/rectcrop3",
      lead_fid: 11379,
      host_fids: null,
      created_at: "2024-04-08T06:45:33+00:00",
      follower_count: 722,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "degenalpha",
      url: "https://warpcast.com/~/channel/degenalpha",
      name: "/degenalpha",
      description: "Best collective alpha intel agency in this app 🎩✨",
      image_url: "https://i.imgur.com/s7tHgUq.gif",
      lead_fid: 331730,
      host_fids: null,
      created_at: "2024-03-07T16:52:22+00:00",
      follower_count: 567,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "shualpha",
      url: "https://warpcast.com/~/channel/shualpha",
      name: "shualpha",
      description:
        "We chat about coins, exploits, yield strategies, news, memes, on chain analysis and more. \n\nFeel right at home, fren.",
      image_url: "https://i.imgur.com/C6BRg0t.jpg",
      lead_fid: 246567,
      host_fids: null,
      created_at: "2024-03-31T12:32:59+00:00",
      follower_count: 540,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "ordinals-alpha",
      url: "https://warpcast.com/~/channel/ordinals-alpha",
      name: "ordinals-alpha",
      description: "ordinals and brc-20 alpha here. \n\nbitcoin layer 2, stax",
      image_url: "https://i.imgur.com/nkbwXax.png",
      lead_fid: 191154,
      host_fids: null,
      created_at: "2024-01-29T15:02:46+00:00",
      follower_count: 464,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "taproot",
      url: "https://warpcast.com/~/channel/taproot",
      name: "Taproot Alpha",
      description: "The home of Bitcoin Ordinals Alpha. Open to everyone!",
      image_url: "https://i.imgur.com/ipamPoO.jpg",
      lead_fid: 288488,
      host_fids: null,
      created_at: "2024-02-05T08:57:09+00:00",
      follower_count: 415,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "fipinsiders",
      url: "https://warpcast.com/~/channel/fipinsiders",
      name: "FIP Insiders (Airdrop Alpha)",
      description: "Your one-stop hub for practical tips to master airdrops",
      image_url: "https://i.imgur.com/thZ5CsI.png",
      lead_fid: 191421,
      host_fids: null,
      created_at: "2024-04-10T09:19:28+00:00",
      follower_count: 401,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "alphacrypto",
      url: "https://warpcast.com/~/channel/alphacrypto",
      name: "alphacrypto",
      description: "da place for AlphaCrypto xD",
      image_url:
        "https://imagedelivery.net/BXluQx4ige9GuW0Ia56BHw/73276ebd-9e13-4988-e4e5-45bf827f7f00/original",
      lead_fid: 301202,
      host_fids: null,
      created_at: "2024-04-15T07:54:01+00:00",
      follower_count: 304,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "airdropsalpha",
      url: "https://warpcast.com/~/channel/airdropsalpha",
      name: "airdropsalpha",
      description: "Follow us to receive alerts about the latest crypto airdrops",
      image_url: "https://i.imgur.com/tJYoAAm.png",
      lead_fid: 6714,
      host_fids: null,
      created_at: "2024-02-11T10:38:30+00:00",
      follower_count: 220,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "alpha-airdrops",
      url: "https://warpcast.com/~/channel/alpha-airdrops",
      name: "OnlyAirdrops",
      description:
        "Airdrop infos will be shared join and make money simple i will share experience in crypto platform to make money sometime my prediction may be wrong but we dont know without trying keep trying.And feel free to discuss anything on this group and enjoy fams.",
      image_url: "https://i.imgur.com/IaDuMve.jpg",
      lead_fid: 244716,
      host_fids: null,
      created_at: "2024-02-01T19:25:56+00:00",
      follower_count: 202,
    },
    {
      _state: {
        adding: false,
        db: "default",
      },
      id: "alps",
      url: "https://warpcast.com/~/channel/alps",
      name: "Alps",
      description:
        "We take the ⌐◨-◨ deep into the pristine pow of the world. Alps is a club where membership fees go into a treasury governed by the membership tokens. If you love mountain culture, skiing, snowboarding, or snow in general 🏂🏔️🚠 Follow & join us at alps.wtf",
      image_url: "https://i.imgur.com/luHGlSH.jpg",
      lead_fid: 803,
      host_fids: null,
      created_at: "2024-02-05T14:05:33+00:00",
      follower_count: 179,
    },
  ],
}
